/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jorginho_LibControl_ravelController */

#ifndef _Included_Jorginho_LibControl_ravelController
#define _Included_Jorginho_LibControl_ravelController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jorginho_LibControl_ravelController
 * Method:    connectRavel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Jorginho_LibControl_ravelController_connectRavel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Jorginho_LibControl_ravelController
 * Method:    ravelSimulate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[I[BILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_Jorginho_LibControl_ravelController_ravelSimulate
  (JNIEnv *, jclass, jstring, jstring, jintArray, jbyteArray, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
